name: Download postal code

on:
  push:
    branches:
      - main
      - workflows
  schedule:
    - cron: '0 0 * * *'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: '16.x'
        cache: 'yarn'

    - run: yarn install --frozen-lockfile

    - name: Create Directory
      run: mkdir -p packages/downloader/out/json

    - name: Download
      run: yarn --cwd packages/downloader run download

    - name: Extract JSON Files
      run: unzip -o packages/downloader/out/postalcode.zip -d packages/downloader/out/json/ > /dev/null

    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        name: postalcode.zip
        path: packages/downloader/out/postalcode.zip

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # tag=v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: packages/downloader/out/json
